# Generated by Django 5.1.4 on 2024-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationtrack', '0002_attendance_city_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='city',
        ),
        migrations.AddField(
            model_name='attendance',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
