# Generated by Django 5.1.4 on 2024-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationtrack', '0003_remove_attendance_city_attendance_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
